# Generated by Django 5.0.2 on 2025-03-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details',
            old_name='cif_nif',
            new_name='cif_cif',
        ),
    ]
