# Generated by Django 5.0.2 on 2025-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cif_nif_client_details_cif_cif'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
    ]
