# Generated by Django 5.0.2 on 2025-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_providers_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cif_cif', models.CharField(max_length=50, unique=True)),
                ('direction', models.TextField()),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='add_expenses',
        ),
        migrations.AddField(
            model_name='client_details',
            name='postal_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
