# Generated by Django 5.0.2 on 2025-04-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_providers_details_delete_add_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_no', models.CharField(max_length=120)),
                ('concept', models.CharField(max_length=120)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client_details')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_providers_details')),
            ],
        ),
    ]
