# Generated by Django 5.0.2 on 2025-04-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details',
            old_name='cif_cif',
            new_name='cif_nif',
        ),
    ]
